### ISSUE TITLE
May need to include "context" parameter to create accurate permalink

### ISSUE THREAD

**Issue by jeremymcwilliams** [alliance-pcsg/primo-explore-report-problem#2]
It seems like docid may not be enough for an accurate permalink. Here's an example of a broken link:

 https://primo.lclark.edu/primo-explore/fulldisplay?docid=TN_oxford10.1093/pan/mpq009&context=L&vid=LCC&search_scope=lcc_nz_pc&tab=default_tab&lang=en_US

If you change the context to "PC", then it works. So unless we can figure out what context can be based upon the docid, may need to include context param from the Primo URL.

**Comment by jeremymcwilliams** [comment]
![screen shot 2017-09-06 at 4 16 38 pm](https://user-images.githubusercontent.com/1103262/30138819-3b56588e-931f-11e7-927b-6be201c41670.png)

**Comment by blakeegee** [comment]
I made a change to the $scope.link value to pull the entire permalink (which includes the context) as opposed to just the docid:
https://github.com/blakeegee/primo-explore-report-problem/blob/cef0c133967ef8fae9a686bf34238cac10221151/js/report-problem.module.js#L19
